<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-UGQAOAUR" failures="1" tests="1" name="Default test(failed)(failed)" time="12.34" errors="0" timestamp="19 Apr 2020 14:32:06 GMT">
  <testcase classname="com.app.Tests.SignOnTest" name="ValidateSignOn" time="1.874">
    <failure type="java.lang.AssertionError" message="expected [http://newtours.demoaut.com/mercurysignon.php] but found [http://newtours.demoaut.com/mercurysignon.php?osCsid=9dce5c2b529b7effb710bcb83ace50d1]">
      <![CDATA[java.lang.AssertionError: expected [http://newtours.demoaut.com/mercurysignon.php] but found [http://newtours.demoaut.com/mercurysignon.php?osCsid=9dce5c2b529b7effb710bcb83ace50d1]
at com.app.Tests.SignOnTest.ValidateSignOn(SignOnTest.java:71)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ValidateSignOn -->
  <testcase classname="com.app.Tests.SignOnTest" name="ValidateWebElementPresent" time="0.0">
    <ignored/>
  </testcase> <!-- ValidateWebElementPresent -->
</testsuite> <!-- Default test(failed)(failed) -->
